# Generated by Django 2.0 on 2019-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qTitle', models.CharField(max_length=25)),
                ('qDescription', models.CharField(max_length=75)),
            ],
        ),
    ]
