# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto.todo_pb2 as todo__pb2


class TodoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddToDo = channel.unary_unary(
        '/TodoService/AddToDo',
        request_serializer=todo__pb2.Txt.SerializeToString,
        response_deserializer=todo__pb2.Empty.FromString,
        )
    self.DeleteToDO = channel.unary_unary(
        '/TodoService/DeleteToDO',
        request_serializer=todo__pb2.Id.SerializeToString,
        response_deserializer=todo__pb2.Empty.FromString,
        )
    self.DoneToDO = channel.unary_unary(
        '/TodoService/DoneToDO',
        request_serializer=todo__pb2.Id.SerializeToString,
        response_deserializer=todo__pb2.Empty.FromString,
        )
    self.GetToDoList = channel.unary_stream(
        '/TodoService/GetToDoList',
        request_serializer=todo__pb2.Empty.SerializeToString,
        response_deserializer=todo__pb2.ToDo.FromString,
        )


class TodoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddToDo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteToDO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DoneToDO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetToDoList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddToDo': grpc.unary_unary_rpc_method_handler(
          servicer.AddToDo,
          request_deserializer=todo__pb2.Txt.FromString,
          response_serializer=todo__pb2.Empty.SerializeToString,
      ),
      'DeleteToDO': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteToDO,
          request_deserializer=todo__pb2.Id.FromString,
          response_serializer=todo__pb2.Empty.SerializeToString,
      ),
      'DoneToDO': grpc.unary_unary_rpc_method_handler(
          servicer.DoneToDO,
          request_deserializer=todo__pb2.Id.FromString,
          response_serializer=todo__pb2.Empty.SerializeToString,
      ),
      'GetToDoList': grpc.unary_stream_rpc_method_handler(
          servicer.GetToDoList,
          request_deserializer=todo__pb2.Empty.FromString,
          response_serializer=todo__pb2.ToDo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TodoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
