"""add_some_random_thing

Revision ID: 430ba05a9955
Revises: 5d24368c1af3
Create Date: 2019-09-26 13:06:11.975643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430ba05a9955'
down_revision = '5d24368c1af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('some_random_thing', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'some_random_thing')
    # ### end Alembic commands ###
